"""
escalations_api.py — Lightweight FastAPI server for the Human Help Dashboard (Day 7).

Runs on port 8080 alongside the main LiveKit voice agent.
The Next.js frontend proxies calls to this server via /api/escalations.

Endpoints:
  GET  /api/escalations                          — list all escalations (newest first)
  GET  /api/escalations/{reference_id}           — get a single escalation
  PATCH /api/escalations/{reference_id}/status   — update status

Start with:
  uv run python src/escalations_api.py
"""

import logging
import sys
from pathlib import Path

# Ensure `src/` is on the path so we can import database.py
sys.path.insert(0, str(Path(__file__).parent))

from dotenv import load_dotenv

load_dotenv(".env.local")

from database import (
    init_db,
    list_escalations,
    update_escalation_status,
    get_call_analytics,
)

try:
    from fastapi import FastAPI, HTTPException, Path as FPath
    from fastapi.middleware.cors import CORSMiddleware
    from pydantic import BaseModel
    import uvicorn
except ImportError as exc:
    raise SystemExit(
        "FastAPI / uvicorn not installed. Run: uv add fastapi uvicorn"
    ) from exc

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger("escalations_api")

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Human Help Escalations API",
    description="Dashboard API for teacher-help requests generated by the voice agent (Day 7).",
    version="1.0.0",
)

# Allow the Next.js dev server (port 3000) and any localhost origin to call us.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
    ],
    allow_credentials=True,
    allow_methods=["GET", "PATCH", "OPTIONS"],
    allow_headers=["*"],
)


# Initialise DB on startup (idempotent — safe even if the agent already did it).
@app.on_event("startup")
def startup_event() -> None:
    logger.info("Initialising database tables (startup)…")
    init_db()
    logger.info("Database ready.")


# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class StatusUpdate(BaseModel):
    status: str  # "OPEN" | "IN_PROGRESS" | "RESOLVED"


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/api/escalations", summary="List all escalations (newest first)")
def get_all_escalations() -> list[dict]:
    """Return all human-help escalation records ordered newest-first."""
    records = list_escalations()
    return records


@app.get(
    "/api/escalations/{reference_id}",
    summary="Get a single escalation by reference ID",
)
def get_escalation(
    reference_id: str = FPath(..., description="e.g. HELP-1042"),
) -> dict:
    """Fetch a single escalation record by its HELP-XXXX reference ID."""
    all_records = list_escalations()
    for rec in all_records:
        if rec.get("reference_id") == reference_id:
            return rec
    raise HTTPException(status_code=404, detail=f"Escalation {reference_id} not found.")


@app.patch(
    "/api/escalations/{reference_id}/status",
    summary="Update the status of an escalation",
)
def patch_status(
    reference_id: str = FPath(..., description="e.g. HELP-1042"),
    body: StatusUpdate = ...,
) -> dict:
    """Update the status to OPEN, IN_PROGRESS, or RESOLVED."""
    result = update_escalation_status(reference_id, body.status)
    if not result.get("success"):
        raise HTTPException(status_code=400, detail=result.get("error", "Update failed."))
    return {"success": True, "reference_id": reference_id, "status": body.status}


@app.get("/api/analytics", summary="Get call analytics dashboard data")
def get_analytics() -> dict:
    """Return metrics and recent call history for Call Analytics Dashboard."""
    return get_call_analytics()


@app.get("/health", summary="Health check")
def health() -> dict:
    return {"status": "ok", "service": "escalations_api"}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    uvicorn.run(
        "escalations_api:app",
        host="0.0.0.0",
        port=8080,
        reload=True,
        log_level="info",
    )
